### ISSUE TITLE
IE 9: Supporting Documents Fail When Form Is Uploaded

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#196]
Looks like the code for supporting docs needs to be updated to use the new Map contract with bulk upload of a object name -> object id. Here's the stacktrace:

In all likelyhood the issue is at ln ~735 in controltypes.js where we haven't updated the legacy support to handle the new map contract from BulkUpload of an object name -> objectId.

This affects our current client.

```
[2015-03-09 16:51:04,039|ERROR|RESTService|genericException|89] Failed to attach supporting docs to the page set instance.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to attach supporting docs to the page set instance.
    at com.tsgrp.opencontent.wizard.core.Wizard2Impl.setUpPsiSupportingDocs(Wizard2Impl.java:1825)
    at com.tsgrp.opencontent.wizard.core.Wizard2Impl.createPageSetInstance(Wizard2Impl.java:578)
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:64)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
    at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:303)
    at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
    at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
    at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
    at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
    at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at com.tsgrp.opencontent.wizard.core.Wizard2Impl.setUpPsiSupportingDocs(Wizard2Impl.java:1812)
    ... 33 more
```

Paging @ladams13 @tconnellytsg

**Comment by mikeblum** [comment]
Revision: 11855
Author: mblum
Date: 2015-03-10 11:23:20.845683
IE 9: WIZARD SUPPORTING DOCS failing to attach to the page set instance. Issue was IE9 was super stringifying the JSON coming back from bulk upload which caused failure in Oc when it tried to parse it was a Map. Closing  https://github.com/tsgrp/ActiveWizard/issues/196

M   /trunk/code/app/modules/wizard/views/controltypes.js
