### ISSUE TITLE
Cannot Create Role / Rule in AW Admin on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#210]
Seems to be related to the `application/xml` mime type that we removed from `oc-config-alfresco.xml` in OC.

```
Caused by: com.tsgrp.wf.exceptions.WFException: 500 Internal Server Error
    at com.tsgrp.wf.tags.GetActivitiesAttrTag.doStartTag(GetActivitiesAttrTag.java:85)
    at org.apache.jsp.jsp.wf_002droles_002doverview_jsp._jspService(wf_002droles_002doverview_jsp.java:476)
    ... 21 more
```

This error happens when clicking 'ok' to save the role.

**Comment by gsteimer** [comment]
This was due to the removal of the `application/xml` mime type from the `oc-config-alfresco.xml` file.  Adding it back in fixed the problem.  Interestingly, even if we ensure that `text/xml` is passed in to the NodeWriter as the mime type, the contents actual mime type is still `application/xml`.  Must be because Alfresco defaults the mime type based on extension?

In any case, fixed in OC REV 11562
CR: Ben
