### ISSUE TITLE
Prevent user from leaving Form checked out

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#242]
Documentum handles the case where a form is left checked out, but there are some major issues in Alfresco.  First, setting this up is relatively simple:
1. Edit an existing form (don't create a new form!)
2. Before finishing the form, either:
   - close the browser  OR
   - Logout of HPI
3.  Log back in to HPI.  

You'll see this in the My Forms Dashlet - Any form left checked out will display the working copy instead of the actual node:
![image](https://cloud.githubusercontent.com/assets/1377228/8622698/652481ae-26f2-11e5-83c3-bfb212277cf4.png)

When you load the WC in the stage, there are a few issues:
- It thinks that the form isn't checked out
  ![image](https://cloud.githubusercontent.com/assets/1377228/8622707/797bb9ec-26f2-11e5-8890-b446e06b88bd.png)
- The Cancel Checkout action doesn't appear in the doc actions (this works in Documentum)
  ![image](https://cloud.githubusercontent.com/assets/1377228/8622725/8bfe5462-26f2-11e5-8a31-c4ffefe793b4.png)

*If you edit the form it fails with this error:
![image](https://cloud.githubusercontent.com/assets/1377228/8622771/c5746632-26f2-11e5-8dc9-f239e11876a0.png)

The error in OC is: 

```
10:32:27,770 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-5] Failed to resume editing the form because it has already been checked out.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to resume editing the form because it has already been checked out.
    at com.tsgrp.opencontent.wizard.action.executer.ResumeFormActionExecuter.executeImpl(ResumeFormActionExecuter.java:41)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
```

I think there's a few things to look at here:
- [ ] Prevent the user from leaving a form checked out.  If the user is editing a form and they leave, prompt the user to either save or discard their changes.  This should work for either logout, browser close, or navigation away from Active Form
- [x] The above solution doesn't totally fix the problem though (ex: session timeout, object left checked out from another tool, etc).  So, we still should fix the issues above:
  - [x] Working copies showing up in saved search.  Should saved search always filter out WC's?
  - [x] Show the checkout user correctly in the stage
  - [x] Allow the lock owner to edit the form
  - [x] Allow the lock owner to cancel the checkout - both within the form, and from a doc action

**Comment by ghost** [comment]
After a lot of research into the alfresco FTS, I have found an issue with they're parsing. Our query was being made correctly according to their documentation, but wasn't getting the correct results.

This query below would not behave correctly, as the parsing of the word NOT did not go as documented, and it would retrieve docs that DID have the aspect workingcopy:
`=cm\:owner:bwhite AND NOT =tsg\:status:Cancelled AND NOT =tsg\:status:Closed AND TYPE:aw\:psi AND NOT ASPECT:cm\:workingcopy`

This query below behaved correctly, and the switch is to use negative signs (-) instead of NOT =  See Below:
`=cm\:owner:bwhite AND -tsg\:status:Cancelled AND -tsg\:status:Closed AND TYPE:aw\:psi AND -ASPECT:cm\:workingcopy`

**Comment by ghost** [comment]
I will update our buildFTSQuery method to solve this problem

**Comment by ghost** [comment]
Fixed the half of this issue so that working copy does not show anymore.
OC - 12062
CR - Dan

@gsteimer Should we switch this issue to an enhancement to prevent the user from leaving a form checked out?

**Comment by gsteimer** [comment]
Yeah, I agree - the rest of this is an enhancement.  I'll update the issue.
