### ISSUE TITLE
Edge1 Edge2, and local builds: can't edit forms

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/ActiveWizard#262]
On edge1, edge 2, and a local alfresco build, getting what looks like a DFC exception when attempting to load a form in the AW Admin.

Build command was ant buildAll -Doverlay=ALFRESCO

<img width="910" alt="screenshot 2015-09-18 00 16 58" src="https://cloud.githubusercontent.com/assets/3905463/9952439/389a81ee-5d9b-11e5-9eb8-3499fc9af828.png">

trace:

```
 2015-09-18 00:13:23,952  DEBUG [enhanced.util.EnhancedAlfrescoLuceneQueryFactory] [http-apr-8080-exec-6] Generated readQuery: (TYPE:aw\:page  AND (@aw\:pageSetName:"Simple CR")) AND NOT ASPECT:\{http\://www.alfresco.org/model/content/1.0\}workingcopy
 2015-09-18 00:13:23,962  DEBUG [alfresco.query.AbstractAlfrescoEmbQueryImpl] [http-apr-8080-exec-6] Total hits: 7
 2015-09-18 00:13:23,972  DEBUG [alfresco.query.AbstractAlfrescoEmbQueryImpl] [http-apr-8080-exec-6] Total results: 7
 2015-09-18 00:13:23,972  INFO  [alfresco.query.AbstractAlfrescoEmbQueryImpl] [http-apr-8080-exec-6] Elapsed Time: 21
 2015-09-18 00:13:23,972  INFO  [alfresco.query.AbstractAlfrescoEmbQueryImpl] [http-apr-8080-exec-6] End enhancedReadQuery
 2015-09-18 00:13:23,993  DEBUG [alfresco.content.AlfrescoEmbContentImpl] [http-apr-8080-exec-1] Begin enhancedGetProperties
 2015-09-18 00:13:24,004  DEBUG [alfresco.content.AlfrescoEmbContentImpl] [http-apr-8080-exec-1] Begin enhancedGetProperties
 2015-09-18 00:13:24,047  DEBUG [core.content.RESTContent] [http-apr-8080-exec-1] Content length is set on the content. Will attempt to stream...
 2015-09-18 00:13:24,048  DEBUG [core.content.RESTContent] [http-apr-8080-exec-1] Range not processed... Sending full content...
 [2015-09-18 00:13:24,054|ERROR|DfiException|logError|96] 
java.lang.NullPointerException
    at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
    at com.tsgrp.wizard.util.WizardUtil.getObjectContents(WizardUtil.java:1574)
    at com.tsgrp.dfi.IAMap.getReadOnlyMap(IAMap.java:780)
    at org.apache.jsp.jsp.ia_005fadmin_005fmanage_005fgroup_005foverview_jsp._jspService(ia_005fadmin_005fmanage_005fgroup_005foverview_jsp.java:232)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at com.tsgrp.wizard.filters.WizardSessionFilter.doFilter(WizardSessionFilter.java:210)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by gsteimer** [comment]
This is a problem with the OC streaming updates that @benallenallen put in.  I think we're going to revert the change temporarily to accommodate some demos early next week and then try to actually fix the issue mid next week.

**Comment by mikeblum** [comment]
We need to be careful about the rollback, I tried rolling back to the
commits before the memory fixes and ran into the 401 Not Authorised bug.

http://10.1.1.14:8080/WizardAdmin/login

**Comment by gsteimer** [comment]
Fixed by @benallenallen in OC rev 12608

CR: me

**Comment by gsteimer** [comment]
@mikeblum - I pushed edge1 and edge2 builds, so this should be working now

**Comment by mikeblum** [comment]
😃
