### ISSUE TITLE
Cannot Edit a form in review

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#267]
This was supposedly working according to: https://github.com/tsgrp/ActiveWizard/issues/86#issuecomment-73900140

However, when I try to edit a form during the review route on Documentum, I get this error:

![image](https://cloud.githubusercontent.com/assets/1377228/10520367/52776ef2-732f-11e5-85a1-077fb4d56c48.png)

The OC exception is: 

```
Followed by: DfException:: THREAD: TP-Processor6; MSG: [DM_SYSOBJECT_E_NO_DELETE_ACCESS]error:  "No delete access for sysobject named 'GGS SL2_workflow_definition.json'"; ERRORCODE: 100; NEXT: null
    at com.documentum.fc.client.impl.docbase.DocbaseExceptionMapper.newException(DocbaseExceptionMapper.java:57)
    at com.documentum.fc.client.impl.connection.docbase.MessageEntry.getException(MessageEntry.java:39)
    at com.documentum.fc.client.impl.connection.docbase.DocbaseMessageManager.getException(DocbaseMessageManager.java:137)
    at com.documentum.fc.client.impl.connection.docbase.netwise.NetwiseDocbaseRpcClient.checkForMessages(NetwiseDocbaseRpcClient.java:310)
    at com.documentum.fc.client.impl.connection.docbase.netwise.NetwiseDocbaseRpcClient.applyForBool(NetwiseDocbaseRpcClient.java:354)
    at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection$1.evaluate(DocbaseConnection.java:1195)
    at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection.evaluateRpc(DocbaseConnection.java:1129)
    at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection.applyForBool(DocbaseConnection.java:1188)
    at com.documentum.fc.client.impl.docbase.DocbaseApi.paramatarizedPrune(DocbaseApi.java:1025)
    at com.documentum.fc.client.DfSysObject.doPrune(DfSysObject.java:987)
    at com.documentum.fc.client.DfSysObject.prune(DfSysObject.java:974)
    at com.tsgrp.wizard.dctm.tbo.AWDocImpl___PROXY.prune(AWDocImpl___PROXY.java)
    at com.documentum.fc.client.DfSysObject.doDestroyAllVersions(DfSysObject.java:1012)
    at com.documentum.fc.client.DfSysObject.destroyAllVersions(DfSysObject.java:1005)
    at com.tsgrp.wizard.dctm.tbo.AWDocImpl___PROXY.destroyAllVersions(AWDocImpl___PROXY.java)
    at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.deleteObjects(DCTMContentImpl.java:655)
    at com.tsgrp.opencontent.wizard.workflow.Wizard2WorkflowImpl.removeWorkflowDefinition(Wizard2WorkflowImpl.java:1560)
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:59)
```

It seems to be an ACL issue, but I don't know what has changed recently with the ACLs.

**Comment by gsteimer** [comment]
No sure how this worked in the past, but the error makes sense - the `wf_approval_details` object gets the `wizard_wizard_acl`.  This ACL only gives delete access to the `dm_owner` and `admingroup`.

@dgrumieaux @benallenallen - what do you guys think?  Wizard contribs have delete access on the `wizard_draft_acl`.  Do we think it's OK to give contribs DELETE access on the `wizard_wizard_acl`?  Or should we create a new ACL for the workflow def?

**Comment by dgrumieaux** [comment]
Should editing in review actually be trying to delete the wiz workflow def in the first place?

**Comment by gsteimer** [comment]
We can talk more about this during the weekly meeting today.  When editing in review, the form _shuold_ re-evaluate workflow rules based on form edits and the workflow summary page should display.  When editing during the approval route, the form _should NOT_ re-evaluate workflow rules.  The entire workflow summary page should be skipped.  

Whether or not the workflow def gets deleted, it'll definitely need to be updated during review routes.

**Comment by gsteimer** [comment]
Update - it seems like this is only happening in approval routes.  Could this be because it's not processing the workflow rules?

@mikeblum

**Comment by mikeblum** [comment]
*\* OC Update Required **

r12950 | mblum | 2015-10-22 17:09:25 -0500 (Thu, 22 Oct 2015) | 1 line

WIZARD WORKFLOW DEFINITION: deleting a workflow definition (case where a form with workflow has no approvers) can safely be deleted by non-form owners. CR dgrumieuax

HPI:

r13518 | mblum | 2015-10-22 16:57:33 -0500 (Thu, 22 Oct 2015) | 1 line

WIZARD WORKFLOW: fix for depending on the form type - can't depend on the url, need to look at the psi's psdNAme attribute

r13516 | mblum | 2015-10-22 16:16:01 -0500 (Thu, 22 Oct 2015) | 1 line

WIZARD WORKFLOW PROCESSING: we now always recompute the wizard workflow definition even if the workflow summary page isn't shown as during a Pending Approval route.
