### ISSUE TITLE
IE9: Supporting Docs causing upload failure

### ISSUE THREAD

**Issue by bridgetbol** [tsgrp/ActiveWizard#279]
When creating a form using IE9, an error message occurs stating, "Failed to get resource /OpenContent/rest/action/execute 500 Failed to retrieve questions and answers from the page set instance." 

```
[2015-10-29 09:16:52,510|WARN |OCUtil|enhancedCompleteObjectToOpenContentObject|582] There is no mimeType for object with id: 0b0003ef8000b689
[2015-10-29 09:16:52,526|ERROR|RESTService|genericException|89] Failed to retrieve questions and answers from the page set instance
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to retrieve questions and answers from the page set instance
        at com.tsgrp.opencontent.wizard.PSIJSONUtil.getSupportingDocsFromPageSetInstance(PSIJSONUtil.java:216)
        at com.tsgrp.opencontent.wizard.PSIJSONUtil.resolveSupportingDocRelations(PSIJSONUtil.java:55)
        at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:83)
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
        at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:316)
        at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:189)
        at sun.reflect.GeneratedMethodAccessor372.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.json.JSONException: JSONObject["id"] not found.
        at org.json.JSONObject.get(JSONObject.java:498)
        at org.json.JSONObject.getJSONObject(JSONObject.java:592)
        at com.tsgrp.opencontent.wizard.PSIJSONUtil.getSupportingDocsFromPageSetInstance(PSIJSONUtil.java:202)
        ... 29 more
```

**Comment by mikeblum** [comment]
r13605 | mblum | 2015-10-29 17:25:58 -0500 (Thu, 29 Oct 2015) | 1 line
Changed paths:
   M /trunk/code/app/modules/wizard/views/controltypes.js

WIZARD + IE 9: Support for radio buttons in IE 9 and uploading supporting docs. For some reason this issue with supporting docs has been stealthy up to this point. Here is an interesting article as to why the assumption of having a listener doesn't work. http://missioncriticallabs.com/blog/lessons-learned-from-jquery-file-upload
