### ISSUE TITLE
Non-required select box errors on PDF creation

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/ActiveWizard#281]
Form with non-required select box and no value selected throws an error on PDF creation.

Snippet from error:
Caused by: org.json.JSONException: JSONObject["value"] not found.
       at org.json.JSONObject.get(JSONObject.java:516)
       at org.json.JSONObject.getString(JSONObject.java:687)
       at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:440)
       ... 41 more

**Comment by mikeblum** [comment]
This will be an OC fox in PSIJSONUtil:jsonToPdf. We may also want to look at indexQuestionsAndAnswers in the same file. Can we go ahead and create a TS Non-Required questions with each page having the same question (required vs non-required). 

To date this has been fixed on a per-client form basis - lets resolve it once and for all.
- [ ] Select Box
- [x] Date box
- [ ] Multi Text Input
- [ ] Multi Select (TossAcross)
- [ ] WYSWIG - should be taken care of in TS WYSWIG 

I want to say this issue only affects object-as-a-value controls that use queries and disaplay value/values such as the above controls (Dates are weird anyways)

**Comment by gsteimer** [comment]
I'm surprised we don't have a TS page set yet.  Let's call it `TS Optional Questions` though
