### ISSUE TITLE
Form creation fails intermittently

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#287]
When creating a form, sometimes the PDF rendition fails with the following error:

```
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating pdf rendition of wizard form!
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:649)
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:56)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:183)
    at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:321)
Caused by: org.json.JSONException: JSONObject["value"] not found.
    at org.json.JSONObject.get(JSONObject.java:498)
    at org.json.JSONObject.getString(JSONObject.java:669)
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:440)
    ... 35 more
```

From talking to @mikeblum, we think it may be an intermittent issue with non-required text fields.

**Comment by alieblich** [comment]
fixed in OC rev 13711
