### ISSUE TITLE
Passthrough Queries Fail

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#291]
On edge1, all of the queries on the TS Passthrough Queries form fail with the error below:

```
2016-04-18 10:40:31,210 37722812    TP-Processor7   ERROR   RESTService java.util.LinkedHashMap cannot be cast to java.lang.String
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
    at com.tsgrp.opencontent.wizard.core.Wizard2Impl.executeAWQueryAction(Wizard2Impl.java:1045)
    at com.tsgrp.opencontent.wizard.core.RESTWizard2.executeWizardQuery(RESTWizard2.java:155)
```

Forms like Simple CR that use query beans seem to be working fine...

**Comment by mikeblum** [comment]
r14216 | mblum | 2016-04-18 15:16:44 -0500 (Mon, 18 Apr 2016) | 1 line
Changed paths:
   M /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/core/Wizard2Impl.java

don't try to stringify HashMap parameters for Passthrough queries - TS Cascading Queries back to normal. Closing https://github.com/tsgrp/ActiveWizard/issues/291
