### ISSUE TITLE
Cannot work with user rules until users are added to the role

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#303]
When creating a role, the users list in the role defaults to empty:

![image](https://user-images.githubusercontent.com/1377228/51928731-31edc280-23bc-11e9-88e6-f5510e81cdd6.png)

With this list empty, the User Rules section fails when you click the `New Rule` button a server error (see below).

To workaround the issue, add at least one user to the role before working with User Rules.

Error on the server is:

```
javax.servlet.ServletException: javax.servlet.jsp.JspException: java.io.IOException: Stream closed
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:861)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:794)
	at org.apache.jsp.jsp.wf_002duser_002drule_002ddetail_jsp._jspService(wf_002duser_002drule_002ddetail_jsp.java:622)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.tsgrp.wizard.filters.WizardSessionFilter.doFilter(WizardSessionFilter.java:210)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
...
Caused by: java.io.IOException: Stream closed
	at org.apache.jasper.runtime.JspWriterImpl.ensureOpen(JspWriterImpl.java:204)
	at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:312)
	at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:342)
	at com.tsgrp.wf.tags.GetWfRuleUsersTag.doEndTag(GetWfRuleUsersTag.java:201)
	at org.apache.jsp.jsp.wf_002duser_002drule_002ddetail_jsp._jspService(wf_002duser_002drule_002ddetail_jsp.java:520)
	... 27 more
```

**Comment by gsteimer** [comment]
Note - just tried this on edge2 and it works fine, so marking this issue as Documentum
