### ISSUE TITLE
Group-based routes on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#75]
The wizard admin cannot setup a group based route due to the `AlfrescoEmbUserImpl#getGroups` method not being implemented.

Once this is implemented, we will need to test that the rest of the admin behaves correctly as well as actually routing forms to a group.

**Comment by gsteimer** [comment]
Update - the `AlfrescoEmbUserImpl#getGroups` has been implemented, but starting an approval route using `TS Group Based Workflow` on edge2 still fails.  The error in the log is:

``` Console
13:46:46,804 ERROR [com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice] [ajp-apr-8009-exec-8] An unspecified OC exception occurred
com.tsgrp.opencontent.core.exception.OCRuntimeException: Could not start workflow.
    at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.startWorkflow(ActivitiWorkflowImpl.java:350)

...

Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Error getting approval details for form.
    at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetAndMaintainApprovalDetails(ActivitiClientWizardWorkflowImpl.java:309)
    at com.tsgrp.opencontent.wizard.activiti.workflow.listener.PrepareWizardApprovalServiceTask.execute(PrepareWizardApprovalServiceTask.java:77)
    at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)

...

Caused by: java.lang.NullPointerException
    at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetAndMaintainApprovalDetails(ActivitiClientWizardWorkflowImpl.java:258)

```

@dgrumieaux - see the last error in the Caused By stack.  Does the "reset and maintain" functionality clash somehow with group-based tasks?

**Comment by gsteimer** [comment]
Just tested this on Alfresco (edge2) and it's working fine after https://github.com/tsgrp/hpi/issues/595 was fixed.
